/**
 * The two documents `rover init` produces: `ROVER.md`, which an agent reads before its first
 * call, and the short block that goes in whichever file its agent already reads.
 *
 * **`ROVER.md` is generated, and that is the point of it rather than a detail of it.** The
 * alternative — a page each project writes by hand — drifts the moment a verb is renamed or a
 * refusal reason is added, and it drifts silently, in somebody else's repository, where nothing
 * in this one can see it. Generated, it is regenerated by re-running init, and
 * `tests/unit/cli/init.test.ts` holds its verb list against `IPC_METHODS` here, so a verb that
 * lands with no line in this file is a red test in this repository rather than a gap in a
 * project that borrowed a device once. It is `ai/RULES.md` §4's "a skill that drifts is a bug
 * like any other", applied to the one document this tool writes into somebody else's checkout.
 *
 * The **snippet** is deliberately tiny and says nothing `ROVER.md` says. It exists to be a
 * trigger — the words a human actually types when they want a manual test — and to name the
 * file that carries the rest. An agent file is a project's own prose, and the less of it Rover
 * occupies the more likely it is to survive.
 *
 * Both are plain string builders with no IO, so the command owns every write.
 */

/** The generated page, written into the project being onboarded. */
export const DOCUMENT_FILE = 'ROVER.md';

/**
 * The markers the snippet is fenced with, which are what make `--write` idempotent: a second
 * run replaces what is between them instead of appending a second copy.
 */
export const SNIPPET_BEGIN = '<!-- rover:begin -->';
export const SNIPPET_END = '<!-- rover:end -->';

/**
 * What makes a generated page **recognisable**, on the first line a reader sees and in the same
 * vocabulary as the fences above.
 *
 * It is load-bearing rather than decorative. A second `rover init` has to find the page it wrote
 * last time — which a human may since have moved into `docs/`, renamed, or both
 * (`./locate.ts`) — and the only honest way to know a markdown file is ours is that we put a
 * mark in it. Matching on the filename alone would let init overwrite somebody else's
 * `ROVER.md`, and matching on nothing at all would scatter a new copy at the root every time
 * the file was tidied away.
 */
export const DOCUMENT_MARKER = '<!-- rover:document';

/**
 * The header the first shipped version of this command wrote, before there was a marker.
 *
 * A page from that build is genuinely ours and has to keep being recognised as ours: without
 * this, the very first re-run over such a project either scatters a second page beside the
 * moved one or — worse — refuses outright, because the guard that protects somebody's own
 * `ROVER.md` cannot tell the two apart. **Delete this once no page from that build survives**;
 * it is a transition, not a second marker.
 */
const UNMARKED_HEADER = 'Re-run it to update; edits here are';

/** Whether this text is a page a previous `rover init` wrote, and may therefore be replaced. */
export function isGeneratedDocument(contents: string): boolean {
	return contents.includes(DOCUMENT_MARKER) || contents.includes(UNMARKED_HEADER);
}

/**
 * The agent files init looks for, in the order it reports them.
 *
 * All three, because a project is often read by more than one agent and Rover has no way to
 * know which one will be pointed at it. Nothing is created except when there is none of them
 * and the caller asked for one to be written.
 */
export const AGENT_FILES = ['CLAUDE.md', 'AGENTS.md', 'GEMINI.md'] as const;

/** The one init creates when a project has no agent file at all — the cross-agent name. */
export const DEFAULT_AGENT_FILE = 'AGENTS.md';

/** What the generated page says about *this* project, as opposed to about Rover. */
export interface DocumentFacts {
	/** The project identifier every lease on it is attributed with. */
	readonly project: string;
	/** The applications the host stops when a lease ends — and what `launch_app` is given. */
	readonly apps: readonly string[];
	/** What `install_app` runs on the host, or `undefined` when this project declares nothing. */
	readonly install: string | undefined;
	/** Whether the MCP server was pointed at a hook file, so `project` may be left out (D22). */
	readonly projectDefaulted: boolean;
	/** Whether the devices are on another machine, which changes what a human can go and check. */
	readonly remote: boolean;
	/** How `rover` is typed on the machine init ran on (`src/cli/_shared/output.ts`). */
	readonly invocation: string;
}

/**
 * The block a project's agent file gets.
 *
 * Every clause in it is load-bearing. The quoted phrases are the **trigger**: an agent that has
 * only been told "Rover is available" shells out to the platform's own tools the first time
 * somebody says "check it on the device", because nothing connected the two. "Rather than asking a human" is there
 * because the other failure is an agent that stops and delegates the tap. And the pointer to the
 * page is last, so the rules arrive before the first call rather than after it — by its real
 * path, wherever the page has been moved to, because a snippet naming a file that is not there
 * teaches an agent that this block is out of date.
 */
export function agentSnippet(documentPath: string): string {
	return [
		SNIPPET_BEGIN,
		'## Manual testing — drive the device with Rover',
		'',
		'A real device is available to this project through the `rover` MCP server. When the work',
		'calls for a **manual test** — "check it on the device", "does this actually work", a',
		'screenshot, a repro, walking through a flow — drive the device with those tools rather than',
		'asking a human to tap something or shelling out to `adb`.',
		'',
		`Read \`${documentPath}\` before the first call: it carries the lease loop, the verb set,`,
		'and the rules that keep a run honest.',
		SNIPPET_END,
	].join('\n');
}

/** The generated page, whole. */
export function roverDocument(facts: DocumentFacts): string {
	return [
		...heading(facts),
		...thisProject(facts),
		...theLoop(facts),
		...theVerbs(),
		...theRules(),
		...whenItDoesNotWork(facts),
	].join('\n');
}

/**
 * `existing` with the snippet in it: replaced between the markers, or appended.
 *
 * Appended with one blank line and no heading of its own beyond the snippet's, because the file
 * this lands in is somebody's own document and init has no idea what it is structured like.
 */
export function withSnippet(existing: string | undefined, snippet: string): string {
	const contents = existing ?? '';
	const begin = contents.indexOf(SNIPPET_BEGIN);
	const end = contents.indexOf(SNIPPET_END);
	if (begin !== -1 && end > begin) {
		return contents.slice(0, begin) + snippet + contents.slice(end + SNIPPET_END.length);
	}
	const body = contents.trimEnd();
	return body === '' ? `${snippet}\n` : `${body}\n\n${snippet}\n`;
}

/** Whether `contents` already carries a Rover block, so a report can say "updated". */
export function hasSnippet(contents: string): boolean {
	return contents.includes(SNIPPET_BEGIN) && contents.includes(SNIPPET_END);
}

/**
 * The `.md` file a one-line agent file points at, or `null` when this is a real document.
 *
 * Both repositories this was written against — Rover's own and its test fixture — have a
 * `CLAUDE.md` whose entire content is "read `ai/RULES.md`", and a project that keeps its rules
 * behind a pointer means it **deliberately**: appending to the pointer puts a section where the
 * agent was told not to look, and quietly grows a file whose whole value is that it is one line.
 * So init names the target and lets a human place the block, which is the one case where asking
 * is cheaper than being wrong.
 *
 * The bound is what keeps this from firing on a real document that happens to mention a
 * markdown file in its first paragraph.
 */
export function pointerTarget(contents: string): string | null {
	const text = contents.trim();
	if (text === '' || text.length > POINTER_MAX_CHARACTERS) {
		return null;
	}
	const named = POINTED_AT.exec(text)?.[1];
	// A file whose one line is "read ROVER.md" is not a pointer at somebody's rulebook — it is
	// this command's own snippet, already placed, and following it would be a loop.
	return named === undefined || named.endsWith(DOCUMENT_FILE) ? null : named;
}

/** Long enough for a sentence or two of instruction, short enough to be no one's rulebook. */
const POINTER_MAX_CHARACTERS = 400;

/** A markdown path, whether or not it is written in backticks. */
const POINTED_AT = /`?([\w./-]+\.md)`?/;

function heading(facts: DocumentFacts): string[] {
	return [
		'# Rover — driving this project on a real device',
		'',
		`${DOCUMENT_MARKER} — generated by \`${facts.invocation} init\`. Re-run that to update`,
		'     it; edits made here are overwritten. Moving or renaming this file is fine: the next',
		'     run finds it by this marker and rewrites it where it is. -->',
		'',
		'A real mobile device is available to this project through **Rover**, an MCP server called',
		'`rover`. It gives an agent hands and eyes on the device: it moves the device and reports',
		'what is on it.',
		'',
		'**Any time the work calls for a manual test, this is how it is done.** "Check it on the',
		'device", "does this actually work", "take a screenshot", "reproduce the bug", "walk through',
		'the flow" — all of them mean the tools below. Never ask a human to tap something you could',
		'tap, and never reach for `adb`: the device is **leased**, and a command run outside the',
		'lease drives hardware another agent may be holding right now.',
		'',
		'## Rover asserts nothing',
		'',
		'It is not a test framework. Nothing here goes red on its own and nothing is a CI gate.',
		'Rover moves the device and tells you what is on the screen; **deciding whether that is',
		'correct is your job**. Say what you saw, quote the evidence, give the verdict yourself —',
		'and when you could not look at all, say that plainly rather than letting silence read as',
		'"checked".',
		'',
	];
}

function thisProject(facts: DocumentFacts): string[] {
	const apps =
		facts.apps.length === 0
			? [
					'- **Applications**: none registered. `launch_app`, `stop_app` and `clear_app_data`',
					'  still work — you pass the `appId` yourself — but the host stops nothing on this',
					"  project's behalf when a lease ends.",
				]
			: [
					`- **Application${facts.apps.length === 1 ? '' : 's'}**: ` +
						`${facts.apps.map((app) => `\`${app}\``).join(', ')} —`,
					'  what `launch_app` is given, and what the host stops on the device when a lease',
					'  ends.',
				];
	const install =
		facts.install === undefined
			? [
					'- **Install**: this project declares none, so `install_app` answers',
					'  `install-hook-undeclared` by name rather than doing something plausible. Get the',
					'  application onto the device some other way, or add an `install` to the hook file.',
				]
			: [
					'- **Install**: `install_app` runs, on the host, with the leased device in its',
					`  environment:\n\n  \`\`\`\n  ${facts.install}\n  \`\`\`\n`,
					'  It is a build, so **it can take up to five minutes**. That is not a hang.',
				];
	return [
		'## This project',
		'',
		`- **Project**: \`${facts.project}\` — the attribution every lease on it carries, and`,
		"  the name the host looks up to find this project's hooks.",
		...apps,
		...install,
		facts.projectDefaulted
			? [
					'- `acquire_device` may leave `project` out: this MCP server was pointed at the',
					'  hook file, and takes the identifier from it.',
				].join('\n')
			: [
					'- `acquire_device` needs `project` spelled out: no hook file is configured for',
					'  this server.',
				].join('\n'),
		facts.remote
			? '- The devices are on **another machine**. Everything below is unchanged — verbs run where\n  the hardware is — but nothing you see locally tells you anything about them.'
			: '- The devices are attached to **this machine**.',
		'',
	];
}

function theLoop(facts: DocumentFacts): string[] {
	return [
		'## The loop',
		'',
		'1. **`list_devices`** — a free device has `heldBy: null`; a held one names its holder and',
		'   how much longer they have. `stale: true` means the host has **no view** of what is',
		'   attached, so an empty list means *no view*, not *no devices* — never read it as "nothing',
		'   is connected".',
		`2. **\`acquire_device\`** — \`serial\`${facts.projectDefaulted ? '' : ', `project`'}, \`owner\` (who this lease is for: an`,
		'   issue, a PR, the task you are on) and `testName` (what you are checking — it names',
		"   this run's directory in the host's artifact archive). `testDescription` is optional and",
		'   is where to say what this run is actually about, in a sentence or two: it names no',
		'   directory, the operator sees it beside the device while you drive it, and the host files',
		'   it with the run. The returned **`lease.leaseId` is the credential** every later call',
		'   carries and the only thing that can release the lease.',
		'3. **`install_app`** — takes the lease id and nothing else. There is no package argument by',
		"   design: what installing means here is the host operator's own configuration.",
		'4. **`launch_app`**, then drive and read.',
		'5. **`release_device`** — **always**, including when the check failed, when you are',
		'   interrupted, and when you gave up. The host restores what it changed on release and on',
		'   expiry, but a lease you walk away from blocks the next agent until its TTL runs out.',
		'',
	];
}

function theVerbs(): string[] {
	return [
		'## The verbs',
		'',
		'Tool names are `snake_case`; their arguments are `camelCase` — `launch_app` takes `leaseId`',
		'and `appId`, never `lease_id`. Copy the property names out of the schema each tool',
		'advertises; a call that mixes the two is refused loudly, naming both keys.',
		'',
		'| What | Tools |',
		'| --- | --- |',
		'| Input | `tap`, `long_press`, `swipe`, `scroll`, `type_text`, `press_key` |',
		'| Waiting | `wait_for`, `wait_until_gone` |',
		'| Reading | `read_screen`, `screenshot`, `device_info`, `read_logs`, `record_video` |',
		'| Application | `launch_app`, `stop_app`, `clear_app_data`, `install_app` |',
		'| Environment | `set_airplane_mode`, `set_wifi` |',
		'| Devices and leases | `list_devices`, `acquire_device`, `release_device`, `status` |',
		'',
	];
}

function theRules(): string[] {
	return [
		'## The rules',
		'',
		'- **Never sleep, and never poll by hand.** Waiting is `wait_for` or `wait_until_gone`, on a',
		'  condition, with a timeout. If the condition you want is missing, say so — a fixed delay',
		'  is how a run goes green against a screen that had not finished rendering.',
		'- **Never reuse a coordinate from an earlier turn.** Every verb resolves its target from a',
		'  freshly captured screen; say *what* you are aiming at, not where it was last time.',
		'- **`read_screen` for structure, `screenshot` for pixels.** `read_screen` gives you element',
		'  ids and rectangles, and it is the read that survives a screen a `screenshot` cannot',
		'  capture. **A black screenshot is a true answer**, not a failed capture: some screens block',
		'  capture, and `read_screen` is what you reach for then.',
		'- **Every action answers with the state after itself**, so you never have to guess whether',
		'  it landed. Read that answer instead of taking another screenshot to find out.',
		'- **A missing capability fails loudly, by name** — the capability, the serial, the platform.',
		'  That is an honest "this device cannot do that". Do not route around it with `adb`.',
		'- **A refusal is not a pass.** `held`, `gone`, `not-attached`, `not-ready` and',
		'  `service-failed` are five different next moves, and none of them is "carry on as though',
		'  the check ran". If you could not get a device, report that the manual test did not happen.',
		'- **The lease id is a credential; the owner string is not.** Do not log the lease id into',
		'  anything shared, and do not expect anyone else to be able to release your lease for you.',
		'',
	];
}

function whenItDoesNotWork(facts: DocumentFacts): string[] {
	return [
		'## When it does not work',
		'',
		'From a terminal, with no agent in the picture:',
		'',
		'```bash',
		`${facts.invocation} status   # which host answered, its pid and uptime`,
		`${facts.invocation} list     # what is attached, what is free, and who holds what`,
		'```',
		'',
		facts.remote
			? 'Neither answers here without `ROVER_HOST_ADDRESS`, `ROVER_HOST_PORT` and\n`ROVER_HOST_TOKEN` in the environment: the host is somebody else’s machine and this one is\nonly a client of it.'
			: 'The local host starts itself on the first call, so nothing needs starting by hand. If\n`status` answers and `list` is empty, the question is a cable or a device that is not\nrunning, not Rover.',
		'',
	];
}
